<?xml version="1.0" encoding="utf-8"?>
<!-- MSBuild props that inject vcpkg include/lib paths for DXC -->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VcpkgRoot>C:\Users\fchil\source\repos\vcpkg</VcpkgRoot>
    <VcpkgManifestMode>true</VcpkgManifestMode>

    <VcpkgInstalledRoot>$(MSBuildProjectDirectory)\vcpkg_installed</VcpkgInstalledRoot>
    <VcpkgTriplet>x64-windows</VcpkgTriplet>

    <VcpkgIncludePath>$(VcpkgInstalledRoot)\$(VcpkgTriplet)\include</VcpkgIncludePath>
    <VcpkgLibPath>$(VcpkgInstalledRoot)\$(VcpkgTriplet)\lib</VcpkgLibPath>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(VcpkgIncludePath);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(VcpkgLibPath);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>dxcompiler.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>
